Collections
startupcolor/2022-Csharp-3 pull request #1
Opened 2021-12-19 22:39 UTC by startupcolor

2021-12-20 19:20 UTC, ausmoons requested changes

2021-12-20 19:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise_4_collections/Program.cs
> +            static void Main(string[] args)
Nav tukšas rinda, tab nav pareizi

2021-12-20 19:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise_4_collections/Program.cs
> +            else if (result == 4)
Kāpēc tieši 4?

2021-12-20 19:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/FlightPlanner/FlightPlanner.cs
> +
Liekas rindas

2021-12-20 19:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/Histogram/Program.cs
> +
Lieka tukša rinda

2021-12-20 19:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/ListExercise1/Program.cs
> +        private static void Main(string[] args) {
{ jaunā rindā

2021-12-20 19:20 UTC, ausmoons commented on csharp-basics/exercises/Collections/ListExercise5/Program.cs
> +            colors[2] = colors[2].Replace("Violet", "Yellow");
var vienkārši colors[2].Replace("Violet", "Yellow");

2021-12-29 18:48 UTC, startupcolor commented on csharp-basics/exercises/Collections/Exercise_3_Collections/Program.cs
> +
tukšā rinda izdzesta

2021-12-29 18:50 UTC, startupcolor commented on csharp-basics/exercises/Collections/Exercise_3_Collections/Program.cs
> +
Tukšā rinda izdzēsta

2021-12-29 18:53 UTC, startupcolor commented on csharp-basics/exercises/Collections/Exercise_4_collections/Program.cs
> +            public static int isHappyNumber(int number)
Lielais burts nomainīts.

2021-12-29 19:10 UTC, startupcolor commented on csharp-basics/exercises/Collections/Exercise_4_collections/Program.cs
> +            else if (result == 4)
WIKI: Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number either equals 1 (where it will stay), or it loops endlessly in a cycle that does not include 1. Those numbers for which this process ends in 1 are happy numbers, while those that do not end in 1 are unhappy numbers (or sad numbers). Teorētiski varēja pielīdzināt  ja nav vienāds ar 1 būtu tas pats , kas manam 4. jo 4 secība beigsies bezgalīgā ciklā 4, 16, ... kas vienkāŗsi vienmēr ir unhappy.

2021-12-29 19:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise_3_Collections/Program.cs
> +
neredzu un arī izmaiņas neuzrāda pie conversation

2021-12-29 19:47 UTC, startupcolor commented on csharp-basics/exercises/Collections/ListExercise5/Program.cs
> +            colors[2] = colors[2].Replace("Violet", "Yellow");
Tas nepatika , jo tad man pasvītroja ar zilu viļņotu līniju vārdu Replace.

2022-01-03 19:45 UTC, ausmoons approved these changes

2022-01-09 21:52 UTC, merged