Arithmetic
startupcolor/2022-Csharp-3 pull request #4
Opened 2022-01-04 00:48 UTC by startupcolor

Arithmetic visi liekie ir izdzēsti.

2022-01-05 16:52 UTC, ausmoons requested changes

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/10-3/Program.cs
> +
Lieka tukša rinda

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/10-3/Program.cs
> +            private static bool MainMenu()
Starp metodēm vajag tukšu rindu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +         public static void CalculateRectangleArea()
Te kkas nav ok ar tabbingu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +                            public static void CalculateTriangleArea()
Starp metodēm vajag tukšu rindu un sakārto tabbingu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +
Lieka tukša rinda

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +
Lieka tukša rinda

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +                    Environment.NewLine + "2. Triangle Area" +
Lieks tabs

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +
Liekas tukšas rindas

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +
šeit nevajag tukšu rindu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +                            //Console.WriteLine("Area of Triangle is:{0}", (ground * height) / 2);
Lieks komentārs un daudz lieku tukšu rindu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Coins/Program.cs
> +                }else
else jaunā rindā

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise6-1/Program.cs
> +            //static void CozaLozaWoza()
Lieki komentāri un liekas tukšas rindas

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise6-1/Program.cs
> +            for (int i = 0; (i <= 11); i++)
Iekavas (i <= 11) ir liekas

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise6-1/Program.cs
> +
Šeit nevajag tukšu rindu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise6/Program.cs
> +
arī beigās nevajag atstāt tukšas rindas

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise8-1/Program.cs
> +            //private double emplPay;
Lieks

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise8-1/Program.cs
> +            }
Starp metodēm vajag tukšu rindu

2022-01-05 16:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise8-1/SalaryCalculator.cs
> +    }
Kas ir šis?

2022-01-06 19:30 UTC, startupcolor commented on csharp-basics/exercises/Arithmetic/Exercise8-1/Program.cs
> +            }
Šis fails kuram bija jābūt izdzēstam. Izdzēsu lokāli datorā vairāk neparādīsies.

2022-01-06 19:30 UTC, startupcolor commented on csharp-basics/exercises/Arithmetic/Exercise8-1/Program.cs
> +            //private double emplPay;
Šis fails kuram bija jābūt izdzēstam. Izdzēsu lokāli datorā vairāk neparādīsies.

2022-01-06 19:30 UTC, startupcolor commented on csharp-basics/exercises/Arithmetic/Exercise6/Program.cs
> +
Šis fails kuram bija jābūt izdzēstam. Izdzēsu lokāli datorā vairāk neparādīsies.

2022-01-06 19:44 UTC, ausmoons approved these changes

2022-01-10 01:10 UTC, merged